export * from './HeroProps';
export * from './InfoGridProps';
export * from './TestimonialProps';
export * from './TestimonialsProps';
export * from './GalleryProps';
export * from './FormProps';
export * from './CartProps';
export * from './PromotionHeaderProps';
export * from './TeamProps';
export * from './FAQProps';
export * from './ContactProps';
export * from './ProductGridProps';
export { Layout } from './Layout';
export * from './headers';
export * from './heroes';
export * from './grids';
export * from './navbars';
export * from './ProductoIndividual';

export { default as ProductGridProps1 } from './ProductGridProps1';
export { default as ProductGridProps2 } from './ProductGridProps2';
